version: '3.8'

services:
  jupyter-lab:
    build: .
    container_name: news_search_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./shared_data:/home/jovyan/shared_data
      - ./app_code:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''